- hosts: localhost
  become_user: root
  tasks:

    - name: Create kubeconfig file
      command: sudo mkdir -p "/etc/config" && touch "/etc/config/admin.conf"
 
    - name: Copy kubeconfig from external files to internal files
      copy: src=../../SHARED/admin.conf dest=/etc/config/admin.conf mode=0777

    - name: Adding KUBECONFIG variable
      delegate_to: localhost
      copy:
        content: export KUBECONFIG="/etc/config/admin.conf/admin.conf"
        dest: /etc/profile.d/kubeconfig.sh
 

 






