- hosts: localhost
  become_user: root
  tasks:
    - name: Copy kubeconfig file to the external folder to share
      copy: src=/etc/kubernetes/admin.conf dest=../../SHARED/admin.conf mode=0777
 






