- hosts: localhost
  become_user: root
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command
  
    - name: Copy join command to local file
      delegate_to: localhost
      copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: ./join-command

    - name: Copy join command to the external file to share
      delegate_to: localhost
      copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: ../../JOIN/join-command







