- hosts: localhost
  become: yes
  tasks:
    - name: Install calico pod network
      become: false
      command: sudo kubectl apply --kubeconfig /etc/kubernetes/admin.conf -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml



